### ISSUE TITLE
Create smaller docker images

### ISSUE THREAD

**Issue by anagrius** [triforkse/logstash-mesos#12]
Currently we need to build images containing both logstash and mesos (i.e for the executor).

Instead we should be able to expose the docker host's mesos-libraries as a volume so that we avoid having to build the mesos files into the image.

We can do the same thing for the logstash files. I.e put them in a volume, map them into the container at runtime and then use a "vanilla" java8 image to run the executor's tasks.

**Comment by epeld** [comment]
The problem we discovered with this approach is that it makes assumptions on the file structure of the mesos slave. That is, we must specify when issuing the task which directories should be mounted as volumes, so we need to guess where the mesos libraries are stored on the slave.
